apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  CREDSTACK_API_PORT: "80"
  CREDSTACK_API_DEBUG: {{ .Values.credstack.api.debug | quote}}
  CREDSTACK_API_PREFORK: {{ .Values.credstack.api.prefork | quote }}
  CREDSTACK_API_SKIP_PREFLIGHT: {{ .Values.credstack.api.skipPreflight | quote}}
  CREDSTACK_ARGON_TIME: {{ .Values.credstack.userCredentials.time | quote }}
  CREDSTACK_ARGON_MEMORY: {{ .Values.credstack.userCredentials.memory | quote }}
  CREDSTACK_ARGON_THREADS: {{ .Values.credstack.userCredentials.threads | quote}}
  CREDSTACK_ARGON_MIN_SECRET_LENGTH: {{ .Values.credstack.userCredentials.minSecretLength | quote }}
  CREDSTACK_ARGON_MAX_SECRET_LENGTH: {{ .Values.credstack.userCredentials.maxSecretLength | quote}}
  # need mongo