apiVersion: v1
kind: Secret
metadata:
  name: credstack-secret
data:
  CREDSTACK_MONGO_HOSTNAME: {{.Values.mongo.config.hostname | b64enc }}
  CREDSTACK_MONGO_PORT: {{ .Values.mongo.config.port | b64enc }}
  CREDSTACK_MONGO_USERNAME: {{ .Values.mongo.config.username | b64enc }}
  CREDSTACK_MONGO_PASSWORD: {{ .Values.mongo.config.password | b64enc }}
  CREDSTACK_MONGO_DEFAULT_DATABASE: {{ .Values.mongo.config.defaultDatabase | b64enc }}
  CREDSTACK_MONGO_AUTH_DATABASE: {{ .Values.mongo.config.authDatabase | b64enc }}
