name: "CLI Build"
run-name: "credstackctl: Build/Release ${{github.ref_name}}"

on:
  workflow_dispatch:
# un-comment this once CLI is properly built
#  push:
#    tags:
#      - "cli/v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '1'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '1'

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Versioning
        id: version
        run: |
          TAG="${GITHUB_REF_NAME#*/}"
          echo "version=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: credstack/credstackctl:latest,credstack/credstackctl:${{ steps.version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
